language: python
python: 3.6
before_install:
  - docker build -t chtka/helloworld .
  - docker run chtka/helloworld bash -c "cd helloworld; pytest"
install:
  - pip install -r requirements.txt
script:
  - pytest
