sudo: required
services:
- docker
language: python
python: 3.6
before_install:
- docker build -t chtka/helloworld:latest .
- docker run chtka/helloworld:latest bash -c "cd helloworld; pytest"
- echo "$DOCKER_PASSWORD"
install:
- pip install -r requirements.txt
script:
- pytest